apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: echo-sink-connector
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: EchoSink
  tasksMax: 3
  config:
    level: INFO
    topics: "kafka-test-apps"
